# ── SNIPPET: molfile_writer_with_bond_orders/Perovskite-ligand-screening_default ─
# Scheduler:   any
# Tool:        any
# Tested:      MD/lib/write_functions.py
# Invariants:
#   - V2000 supports <1000 atoms; abort if exceeded.
#   - Bond order comes from get_bonds(elements,adj_mat) (TAFFI logic).
# Notes: Depends on Hybridization_finder and get_bonds from TAFFI stack (imported via id_types).
# ────────────────────────────────────────────────────────────

from numpy import *
from id_types import *

def mol_write(name,elements,geo,adj_mat,append_opt=False):

    # Consistency check
    if len(elements) >= 1000:
        print("ERROR in mol_write: the V2000 format can only accomodate up to 1000 atoms per molecule.")
        return 

    if append_opt == True:
        open_cond = 'a'
    else:
        open_cond = 'w'

    hybridizations = Hybridization_finder(elements,adj_mat)

    base_name = name.split(".")
    if len(base_name) > 1:
        base_name = ".".join(base_name[:-1])
    else:
        base_name = base_name[0]

    bond_mat = get_bonds(elements,adj_mat)    

    with open(name,open_cond) as f:

        f.write('{}\nGenerated by mol_write.py\n\n'.format(base_name))
        f.write("{:>3d}{:>3d}  0  0  0  0  0  0  0  0  1 V2000\n".format(len(elements),int(sum(adj_mat/2.0))))

        for count_i,i in enumerate(elements):
            f.write(" {:> 9.4f} {:> 9.4f} {:> 9.4f} {:<3s} 0  0  0  0  0  0  0  0  0  0  0  0\n".format(geo[count_i][0],geo[count_i][1],geo[count_i][2],i))

        bonds = [ (count_i,count_j) for count_i,i in enumerate(adj_mat) for count_j,j in enumerate(i) if j == 1 and count_j > count_i ] 
        for i in bonds:
            bond_order = int(bond_mat[i[0],i[1]])
            f.write("{:>3d}{:>3d}{:>3d}  0  0  0  0\n".format(i[0]+1,i[1]+1,bond_order))
        f.write("M  END\n$$$$\n")

    return
