"""
pipeline.plugins.registry – Plugin discovery, validation, and registration.

Validates plugin structure:
  Required: plugin.yaml, scripts/
  Expected: glue/ (generated by `plugin init`)
  Optional: templates/, environment.yml, README.md
"""
from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml

logger = logging.getLogger(__name__)


# ── Public API ───────────────────────────────────────────────────────────

def discover_plugins(plugins_root: Path) -> List[Path]:
    """Return paths to all valid plugin directories under *plugins_root*."""
    if not plugins_root.is_dir():
        return []
    return sorted(
        p for p in plugins_root.iterdir()
        if p.is_dir() and (p / "plugin.yaml").exists()
    )


def load_manifest(plugin_dir: Path) -> Dict[str, Any]:
    """Parse plugin.yaml and return as a dict."""
    manifest_path = plugin_dir / "plugin.yaml"
    if not manifest_path.exists():
        raise FileNotFoundError(f"No plugin.yaml in {plugin_dir}")
    with open(manifest_path, "r") as f:
        return yaml.safe_load(f)


def validate_plugin(plugin_dir: Path) -> List[str]:
    """
    Validate a plugin directory.  Returns a list of error/warning strings;
    an empty list means the plugin is valid.
    """
    errors: List[str] = []
    plugin_dir = Path(plugin_dir).resolve()

    if not plugin_dir.is_dir():
        return [f"Not a directory: {plugin_dir}"]

    # ── Required files ────────────────────────────────────────────────
    if not (plugin_dir / "plugin.yaml").exists():
        errors.append("Missing required file: plugin.yaml")
        return errors

    if not (plugin_dir / "scripts").is_dir():
        # Check if scripts are in the root directory (flat layout)
        _SCRIPT_EXTS = (".py", ".sh", ".bash", ".submit")
        has_root_scripts = any(
            f.is_file() and f.suffix in _SCRIPT_EXTS for f in plugin_dir.iterdir()
        )
        if not has_root_scripts:
            errors.append("No scripts found (checked scripts/ and plugin root)")

    # ── Parse manifest ────────────────────────────────────────────────
    try:
        manifest = load_manifest(plugin_dir)
    except Exception as e:
        return [f"Failed to parse plugin.yaml: {e}"]

    if not manifest.get("name"):
        errors.append("plugin.yaml: missing 'name'")

    # ── Validate stages (if present) ─────────────────────────────────
    stages = manifest.get("stages", [])
    if stages:
        for i, stage in enumerate(stages):
            tag = f"stage[{i}] '{stage.get('name', '?')}'"

            if not stage.get("name"):
                errors.append(f"{tag}: missing 'name'")

            # Check script references exist (if specified)
            script = stage.get("script")
            if script:
                spath = plugin_dir / script
                if not spath.exists():
                    errors.append(f"{tag}: script not found: {script}")

            template = stage.get("template")
            if template:
                tpath = plugin_dir / template
                if not tpath.exists():
                    errors.append(f"{tag}: template not found: {template}")

    # ── Check glue directory ──────────────────────────────────────────
    glue_dir = plugin_dir / "glue"
    if not glue_dir.is_dir():
        errors.append(
            "Missing glue/ directory. Run 'plugin init' to generate "
            "adapter scripts, or create them manually."
        )
    else:
        # Check that at least one executable exists
        glue_files = [f for f in glue_dir.iterdir() if f.is_file()]
        if not glue_files:
            errors.append("glue/ directory is empty — needs at least one script")

    # ── Validate environment file ────────────────────────────────────
    env_cfg = manifest.get("environment", {})
    env_file = env_cfg.get("file")
    if env_file and not (plugin_dir / env_file).exists():
        errors.append(f"environment file not found: {env_file}")

    # ── Check Python imports vs environment (best-effort) ────────────
    _check_imports(plugin_dir, manifest, errors)

    return errors


def register_plugin(plugin_dir: Path) -> Dict[str, Any]:
    """
    Validate and register a plugin.  Returns the manifest dict.
    Raises ValueError if validation fails.
    """
    errors = validate_plugin(plugin_dir)
    if errors:
        msg = "Plugin validation failed:\n" + "\n".join(f"  - {e}" for e in errors)
        raise ValueError(msg)

    manifest = load_manifest(plugin_dir)
    logger.info(
        "Registered plugin '%s' v%s (%d stages)",
        manifest["name"],
        manifest.get("version", "?"),
        len(manifest.get("stages", [])),
    )
    return manifest


# ── Helpers ──────────────────────────────────────────────────────────────

def _check_imports(plugin_dir: Path, manifest: Dict, errors: List[str]) -> None:
    """Best-effort check that Python imports are covered by the environment."""
    env_file = manifest.get("environment", {}).get("file")
    if not env_file:
        return
    env_path = plugin_dir / env_file
    if not env_path.exists():
        return

    try:
        with open(env_path) as f:
            env = yaml.safe_load(f)
        env_pkgs: set[str] = set()
        for dep in env.get("dependencies", []):
            if isinstance(dep, str):
                name = re.split(r"[=<>!]", dep)[0].strip().lower()
                env_pkgs.add(name)
            elif isinstance(dep, dict) and "pip" in dep:
                for pip_dep in dep["pip"]:
                    name = re.split(r"[=<>!]", pip_dep)[0].strip().lower()
                    env_pkgs.add(name)
    except Exception:
        return

    scripts_dir = plugin_dir / "scripts"
    if not scripts_dir.is_dir():
        return

    import_re = re.compile(r"^\s*(?:import|from)\s+(\w+)")
    stdlib = {
        "os", "sys", "re", "json", "csv", "argparse", "pathlib", "tempfile",
        "collections", "concurrent", "subprocess", "itertools", "glob",
        "contextlib", "time", "typing", "math", "copy", "functools",
        "shutil", "io", "textwrap", "logging", "hashlib", "abc",
        "__future__",
    }

    for py_file in scripts_dir.rglob("*.py"):
        with open(py_file, "r", errors="ignore") as f:
            for line in f:
                m = import_re.match(line)
                if not m:
                    continue
                pkg = m.group(1).lower()
                if pkg in stdlib:
                    continue
                if (scripts_dir / pkg).is_dir() or (scripts_dir / f"{pkg}.py").exists():
                    continue
                if pkg not in env_pkgs:
                    logger.debug(
                        "Plugin '%s': import '%s' in %s not obviously in environment",
                        manifest.get("name", "?"), pkg,
                        py_file.relative_to(plugin_dir),
                    )
