#!/bin/bash
# ── glue/runner.sh ─────────────────────────────────────────────────────
# Generated by golddigr plugin system.
# Runs all 6 stages for a single (XYZ, charge) combination.
#
# Usage: ./glue/runner.sh <xyz_file> <charge> <mult> <uhf>
# Must be run from inside a per-job working directory.
set -euo pipefail

XYZ_FILE="${1:?Usage: runner.sh <xyz> <charge> <mult> <uhf>}"
CHARGE="${2:?}"
MULT="${3:?}"
UHF="${4:?}"

PKG_DIR="$(cd "$(dirname "$0")/.." && pwd)"
WORKDIR="$(pwd)"

echo '================================================================'
echo 'golddigr plugin: xtb-freq-tsopt-irc-wbo'
echo "XYZ:    $XYZ_FILE"
echo "Charge: $CHARGE  Mult: $MULT  UHF: $UHF"
echo "Workdir: $WORKDIR"
echo '================================================================'

# Copy input XYZ as input.xyz (expected by pysisyphus templates)
cp "$XYZ_FILE" input.xyz

# ── Stage 1: xTB Frequency ────────────────────────────────────────────
echo "[stage] freq"
xtb "$XYZ_FILE" --hess --chrg "$CHARGE" --uhf "$UHF" --acc 0.2 --iterations 300 --namespace freq

# Gate: imaginary frequency check
LOWEST_FREQ=$(grep -A1 "low/incremental" g98.out 2>/dev/null | tail -1 | awk '{print $1}' || echo "9999")
if [ -z "$LOWEST_FREQ" ]; then LOWEST_FREQ="9999"; fi
PASS=$(python3 -c "f=float('$LOWEST_FREQ'); print('yes' if f < -20 else 'no')" 2>/dev/null || echo "no")
if [ "$PASS" != "yes" ]; then
    echo "[gate] freq: lowest freq=$LOWEST_FREQ, threshold=-20. SKIP."
    echo "GATE_FAILED:freq" >> "$WORKDIR/status.log"
    exit 0
fi
echo "[gate] freq: PASS (freq=$LOWEST_FREQ)"

# ── Stage 2: TSOPT ────────────────────────────────────────────────────
echo "[stage] tsopt"
sed "s/CHARGE_PLACEHOLDER/$CHARGE/g; s/MULT_PLACEHOLDER/$MULT/g" "$PKG_DIR/templates/TSOPT_yaml.template" > run.yaml
pysisyphus run.yaml 2>&1 | tee tsopt.log
true

# Gate: file exists
if [ ! -f "ts_final_geometry.xyz" ]; then
    echo "[gate] tsopt: ts_final_geometry.xyz not found. SKIP."
    echo "GATE_FAILED:tsopt" >> "$WORKDIR/status.log"
    exit 0
fi
echo "[gate] tsopt: PASS (ts_final_geometry.xyz exists)"

# ── Stage 3: IRC ──────────────────────────────────────────────────────
echo "[stage] irc"
sed "s/CHARGE_PLACEHOLDER/$CHARGE/g; s/MULT_PLACEHOLDER/$MULT/g" "$PKG_DIR/templates/TSOPT-IRC_yaml.template" > run.yaml
pysisyphus run.yaml 2>&1 | tee irc.log
true

# Gate: file exists
if [ ! -f "finished_irc.trj" ]; then
    echo "[gate] irc: finished_irc.trj not found. SKIP."
    echo "GATE_FAILED:irc" >> "$WORKDIR/status.log"
    exit 0
fi
echo "[gate] irc: PASS (finished_irc.trj exists)"

# ── Stage 4: Spin/WBO scan ───────────────────────────────────────────
echo "[stage] spin_wbo"
python "$PKG_DIR/scripts/spin_wbo_scan.py" --trj finished_irc.trj --charge $CHARGE --mult -1 --uhf-max 6 --workdir xTB-scan --nprocs 1

# Gate: file exists
if [ ! -f "xTB-scan/spin_scan_summary.csv" ]; then
    echo "[gate] spin_wbo: xTB-scan/spin_scan_summary.csv not found. SKIP."
    echo "GATE_FAILED:spin_wbo" >> "$WORKDIR/status.log"
    exit 0
fi
echo "[gate] spin_wbo: PASS (xTB-scan/spin_scan_summary.csv exists)"

# ── Stage 5: IRC Analysis ────────────────────────────────────────────
echo "[stage] irc_analysis"
python "$PKG_DIR/scripts/yarp_results_builder.py" ./ --charge $CHARGE

# Gate: file exists
if [ ! -f "IRC_Analysis/finished_first/frame_00000.json" ]; then
    echo "[gate] irc_analysis: IRC_Analysis/finished_first/frame_00000.json not found. SKIP."
    echo "GATE_FAILED:irc_analysis" >> "$WORKDIR/status.log"
    exit 0
fi
echo "[gate] irc_analysis: PASS (IRC_Analysis/finished_first/frame_00000.json exists)"

# ── Stage 6: Sankey ──────────────────────────────────────────────────
echo "[stage] sankey"
python "$PKG_DIR/scripts/irc_sankey_zoomsvg_fixed.py" --root IRC_Analysis --topK 999 --min-frac 0.0 --out IRC_Analysis/sankey --window 50

# Gate: directory exists
if [ ! -d "IRC_Analysis/sankey" ]; then
    echo "[gate] sankey: IRC_Analysis/sankey/ not found. SKIP."
    echo "GATE_FAILED:sankey" >> "$WORKDIR/status.log"
    exit 0
fi
echo "[gate] sankey: PASS (IRC_Analysis/sankey/ exists)"

# ── Archive results ──────────────────────────────────────────────────
XYZ_STEM=$(basename "$XYZ_FILE" .xyz)
ARCHIVE_NAME="${XYZ_STEM}_${CHARGE}_${MULT}.zip"
echo "[archive] Creating $ARCHIVE_NAME"
zip -rq "$ARCHIVE_NAME" "xTB-scan/" "IRC_Analysis/" "input.xyz" "ts_final_geometry.xyz" "finished_irc.trj" "finished_first.xyz" "finished_last.xyz" "g98.out" 2>/dev/null || true
echo "DONE" >> "$WORKDIR/status.log"

echo "[done] All stages complete for $XYZ_FILE (charge=$CHARGE)"
