#!/bin/bash
# ── glue/submit_all.sh ─────────────────────────────────────────────────
# Generated by golddigr plugin system.
# Submits one SLURM job per (XYZ, charge) combination.
#
# Usage: cd <package_dir> && ./glue/submit_all.sh
set -euo pipefail

PKG_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PKG_DIR"

# ── Load cluster config ──────────────────────────────────────────────
if [ ! -f "cluster.env" ]; then
    echo "Error: cluster.env not found. Copy cluster.yaml and re-package."
    exit 1
fi
source cluster.env

# Defaults if not set in cluster.env
SLURM_ACCOUNT="${SLURM_ACCOUNT:-PLACEHOLDER}"
SLURM_PARTITION="${SLURM_PARTITION:-cpu}"
SLURM_QOS="${SLURM_QOS:-normal}"
SLURM_NODES="${SLURM_NODES:-1}"
SLURM_NTASKS_PER_NODE="${SLURM_NTASKS_PER_NODE:-1}"
SLURM_TIME="${SLURM_TIME:-04:00:00}"
THROTTLE_MAX_CONCURRENT="${THROTTLE_MAX_CONCURRENT:-10}"
THROTTLE_CHECK_INTERVAL="${THROTTLE_CHECK_INTERVAL:-30}"

# Charges to sample (from plugin.yaml charge_strategy)
CHARGES=(-1 0 1)

BATCHNAME="golddigr"

# ── Element → atomic number lookup (for UHF computation) ─────────────
compute_uhf() {
    local xyz="$1" charge="$2"
    python3 -c "
lines = open('$xyz').readlines()
natom = int(lines[0].strip())
_Z = {'H':1,'He':2,'Li':3,'Be':4,'B':5,'C':6,'N':7,'O':8,'F':9,'Ne':10,
      'Na':11,'Mg':12,'Al':13,'Si':14,'P':15,'S':16,'Cl':17,'Ar':18,
      'K':19,'Ca':20,'Sc':21,'Ti':22,'V':23,'Cr':24,'Mn':25,'Fe':26,
      'Co':27,'Ni':28,'Cu':29,'Zn':30,'Ga':31,'Ge':32,'As':33,'Se':34,
      'Br':35,'Kr':36,'Rb':37,'Sr':38,'Y':39,'Zr':40,'Nb':41,'Mo':42,
      'Tc':43,'Ru':44,'Rh':45,'Pd':46,'Ag':47,'Cd':48,'In':49,'Sn':50,
      'Sb':51,'Te':52,'I':53,'Xe':54,'Cs':55,'Ba':56,'La':57,'Ce':58,
      'Pr':59,'Nd':60,'Pm':61,'Sm':62,'Eu':63,'Gd':64,'Tb':65,'Dy':66,
      'Ho':67,'Er':68,'Tm':69,'Yb':70,'Lu':71,'Hf':72,'Ta':73,'W':74,
      'Re':75,'Os':76,'Ir':77,'Pt':78,'Au':79,'Hg':80,'Tl':81,'Pb':82,
      'Bi':83,'Po':84,'At':85,'Rn':86,'Ac':89,'Th':90,'Pa':91,'U':92}
def _n(s): return s[:1].upper() + s[1:].lower()
total_z = sum(_Z.get(_n(l.split()[0]), 0) for l in lines[2:2+natom] if l.split())
ne = total_z - int($charge)
print(0 if ne % 2 == 0 else 1)
"
}

compute_mult() {
    local uhf="$1"
    echo $(( uhf + 1 ))
}

# ── Throttle helper ──────────────────────────────────────────────────
wait_for_slot() {
    while true; do
        current=$(squeue -u "$USER" -h -o "%j" | grep -cF "$BATCHNAME" || true)
        if (( current < THROTTLE_MAX_CONCURRENT )); then return; fi
        printf '[%s] Queue full (%d/%d). Waiting %ds...\n' \
            "$(date '+%H:%M:%S')" "$current" "$THROTTLE_MAX_CONCURRENT" "$THROTTLE_CHECK_INTERVAL"
        sleep "$THROTTLE_CHECK_INTERVAL"
    done
}

# ── Build env_setup block for SLURM scripts ──────────────────────────
ENV_BLOCK=""
i=0
while true; do
    var="ENV_SETUP_${i}"
    val="${!var:-}"
    [ -z "$val" ] && break
    ENV_BLOCK="${ENV_BLOCK}${val}"$'\n'
    i=$((i + 1))
done

echo '================================================================'
echo 'golddigr plugin: xtb-freq-tsopt-irc-wbo'
echo "Account:    $SLURM_ACCOUNT"
echo "Partition:  $SLURM_PARTITION"
echo "Charges:    ${CHARGES[*]}"
echo "Max jobs:   $THROTTLE_MAX_CONCURRENT"
echo '================================================================'

# ── Main loop ────────────────────────────────────────────────────────
for xyz in xyz/*.xyz; do
    [ -f "$xyz" ] || continue
    xyz_stem=$(basename "$xyz" .xyz)

    for charge in "${CHARGES[@]}"; do
        UHF=$(compute_uhf "$xyz" "$charge")
        MULT=$(compute_mult "$UHF")
        JOB_NAME="${BATCHNAME}-${xyz_stem}_${charge}_${MULT}"

        # Skip if already queued
        if squeue -u "$USER" --noheader -o "%.200j" 2>/dev/null | grep -qF "$JOB_NAME"; then
            echo "[skip] Already queued: $JOB_NAME"
            continue
        fi

        # Create per-job working directory
        WORKDIR="jobs/${xyz_stem}_${charge}_${MULT}"
        mkdir -p "$WORKDIR"
        cp "$xyz" "$WORKDIR/"

        # Write SLURM script
        SUBMIT_FILE="$WORKDIR/job.submit"
        cat > "$SUBMIT_FILE" << SLURM_EOF
#!/bin/bash
#SBATCH --job-name=$JOB_NAME
#SBATCH --output=$JOB_NAME.%j.out
#SBATCH --error=$JOB_NAME.%j.err
#SBATCH --account=$SLURM_ACCOUNT
#SBATCH --partition=$SLURM_PARTITION
#SBATCH --qos=$SLURM_QOS
#SBATCH --nodes=$SLURM_NODES
#SBATCH --ntasks-per-node=$SLURM_NTASKS_PER_NODE
#SBATCH --time=$SLURM_TIME

set -euo pipefail

# Environment
$ENV_BLOCK

cd "\$SLURM_SUBMIT_DIR"
../../glue/runner.sh $(basename "$xyz") $charge $MULT $UHF
SLURM_EOF

        wait_for_slot
        echo "[submit] $JOB_NAME"
        sbatch "$SUBMIT_FILE"
    done
done

echo '================================================================'
echo 'All jobs submitted.'
echo '================================================================'
