# ── SNIPPET: pdb_conect_writer/Perovskite-ligand-screening_default ─
# Scheduler:   any
# Tool:        any
# Tested:      MD/lib/write_functions.py
# Invariants:
#   - Writes CONECT with up to 4 connections per line continuation.
# Notes: Useful for quick visualization.
# ────────────────────────────────────────────────────────────

def pdb_write(name,elements,geo,adj_mat,append_opt=False):

    if append_opt == True:
        open_cond = 'a'
    else:
        open_cond = 'w'

    base_name = name.split(".")
    if len(base_name) > 1:
        base_name = ".".join(base_name[:-1])
    else:
        base_name = base_name[0]

    with open(name,open_cond) as f:

        f.write('COMPND    {}\n'.format(base_name))
        f.write('AUTHOR    Generated by pdb_write.py\n')

        for count_i,i in enumerate(elements):
            f.write("HETATM {:>4d} {:>2s} {:>5s} {:>5d}      {:> 6.3f}  {:> 6.3f}  {:> 6.3f}  1.00  0.00 {:>11s}\n".format(count_i+1,i.upper(),"LIG",1,geo[count_i][0],geo[count_i][1],geo[count_i][2],i))

        con_count = 0
        for count_i,i in enumerate(adj_mat):
            cons = sorted([ count_j+1 for count_j,j in enumerate(i) if j == 1 ])
            if cons > 0:
                for j in range(len(cons)):                
                    if j % 4 == 0:
                        if j == 0:
                            f.write("CONECT {:>4d}".format(count_i+1))
                        else:
                            f.write("\nCONECT {:>4d}".format(count_i+1))
                    f.write(" {:>4d}".format(cons.pop(0)))
                    con_count += 1
                f.write("\n")

        f.write("MASTER        0    0    0    0    0    0    0    0 {:>4d} {:>4d} {:>4d} {:>4d}\n".format(len(elements),0,con_count,0))
        f.write("END\n")

    return
